//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iakademi43_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_siparislerim
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string orderGroupGUID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> UserID { get; set; }
        public string NameSurname { get; set; }
    }
}
